version: '3.8'
services:
        mysql:
                image: mysql:8.0
                container_name: mysql

                environment:
                        MYSQL_ROOT_PASSWORD: hola
                        MYSQL_DATABASE: db_cine
                        MYSQL_USER: springuser
                        MYSQL_PASSWORD: disenio
                ports:
                        - "3306:3306"

                volumes:
                        - "/home/ebloemer/mysql-data-api-cine-ebloemer:/var/lib/mysql"
        pma:
                image: phpmyadmin:5
                container_name: phpmyadmin

                environment:
                        PMA_HOST: mysql
                        PMA_PORT: 3306
                        PMA_ARBITRARY: 1
                ports:
                        - "8081:80"
               
                volumes:
                        - "/opt/phpmyadmin/sessions:/sessions"
                        - "/opt/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
