version: '3.8'
services:
        mysql:
                image: mysql:8.0
                container_name: mysql

                environment:
                        MYSQL_ROOT_PASSWORD: hola
                        MYSQL_DATABASE: db_cine
                        MYSQL_USER: springuser
                        MYSQL_PASSWORD: disenio
                ports:
                        - "3306:3306"

                volumes:
                        - "/home/ebloemer/mysql-data-api-cine-ebloemer:/var/lib/mysql"
        pma:
                image: phpmyadmin:5
                container_name: phpmyadmin

                environment:
                        PMA_HOST: mysql
                        PMA_PORT: 3306
                        PMA_ARBITRARY: 1
                ports:
                        - "8082:80"
               
                volumes:
                        - "/opt/phpmyadmin/sessions:/sessions"
                        - "/opt/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"

        api:
                container_name:  apijava
                build: 
                        context: .
                        dockerfile: Dockerfile
                environment:
                        - DB_HOST=${DB_HOST}
                        - DB_USER=${DB_USER}
                        - DB_PASS=${DB_PASS}
                ports:
                        - "8080:8080"
                env_file:
                        - .env
                volumes:
                        - "./logs/api:/logs"

#Comando para buildear con maven
#mvn clean package -DskipTest
#locahost:8080/swagger-ui.hmtl
